### ISSUE TITLE
Settings not displaying a correct Group title since upgrading to Umbraco 11

### ISSUE THREAD

**Issue by martinlcp** [Infocaster/UrlTracker#102]
**Describe the bug**
[untranslated / not supplied title ? ]

**To Reproduce**
Upgrade from v10 to v11 of Umbraco and UrlTracker

**Expected behavior**
Correct banner

**Screenshots**
![image](https://user-images.githubusercontent.com/883638/205963147-baf114da-3de2-483c-bdf2-e8617e0a2b18.png)

**Comment by D-Inventor** [comment]
Hi @martinjgriffiths ! Thank you very much for your bug report. I'll see if I can reproduce this behaviour and get back to you when I have some results. That should be within 2 days.

**Comment by D-Inventor** [comment]
@martinjgriffiths Can you check which language you have selected for your backoffice account? I've been able to reproduce this behaviour when selecting a language that is not "English (United States)".

If your language is not supported, you can open a pull request with a translation of the language that you want to have supported.

**Comment by martinlcp** [comment]
> 

Yup thats it, mines set to English (United Kingdom)

**Comment by Mohunky** [comment]
I'm getting this on Umbraco v9 + UrlTracker v9.1.1 as well. Language is set to English (United Kingdom)

**Comment by D-Inventor** [comment]
Thank you for letting me know. I'll see if I can fix it. I've probably just forgotten to add the language file for the fallback language

**Comment by D-Inventor** [comment]
@martinjgriffiths I just released a [prerelease 11.0.1-beta.1](https://www.nuget.org/packages/UrlTracker/11.0.1-beta0001) with a fix for this issue. Can you confirm that this version fixes your issue?

@Mohunky I also released a [prerelease 9.1.2-beta.1](https://www.nuget.org/packages/UrlTracker/9.1.2-beta0001) with a fix. Can you confirm that this version fixes the issue on your version?

**Comment by martinlcp** [comment]
> @martinjgriffiths I just released a [prerelease 11.0.1-beta.1](https://www.nuget.org/packages/UrlTracker/11.0.1-beta0001) with a fix for this issue. Can you confirm that this version fixes your issue?
> 
> @Mohunky I also released a [prerelease 9.1.2-beta.1](https://www.nuget.org/packages/UrlTracker/9.1.2-beta0001) with a fix. Can you confirm that this version fixes the issue on your version?

Yup that did the trick for me - thanks for the quick response

**Comment by Mohunky** [comment]
> @martinjgriffiths I just released a [prerelease 11.0.1-beta.1](https://www.nuget.org/packages/UrlTracker/11.0.1-beta0001) with a fix for this issue. Can you confirm that this version fixes your issue?
> 
> @Mohunky I also released a [prerelease 9.1.2-beta.1](https://www.nuget.org/packages/UrlTracker/9.1.2-beta0001) with a fix. Can you confirm that this version fixes the issue on your version?

Fixed! Thank you very much, appreciate the fix and the package :)

**Comment by D-Inventor** [comment]
That makes me happy :D 
I'll do a proper release of this fix either later today or at the latest next week.

**Comment by D-Inventor** [comment]
This issue is fixed in version 9.1.2, 10.2.1 and 11.0.1
