### ISSUE TITLE
Memory Leak using Umbraco 8, UrlTracker 5

### ISSUE THREAD

**Issue by luuksommers** [Infocaster/UrlTracker#112]
**Describe the bug**
Using Umbraco 8.18.5 and UrlTracker 5.2.2 we get a MemoryLeak, with the cache within UrlTracker consuming over 1.2 GB of memory before the app-pool crashes.

**Screenshots**
Below I've inserted 2 snapshots of the memory dump. It looks like the Interceptor cache is not properly cleaning up.

Total memory:

![image](https://user-images.githubusercontent.com/1185823/216369392-2abd7202-4795-4b7c-968f-51e2eea74e07.png)

Detail of the CacheEntry, there were 5 time of these entries holding about 200 Mb of data:

![image](https://user-images.githubusercontent.com/1185823/216369537-506884d1-3f77-4514-8194-21292c7587d4.png)

When we disable the `urlTracker:enableInterceptCaching`, the memory is stable. Could it be that this is caused because of the async methods being stored instead of the result?

**Comment by D-Inventor** [comment]
Hi @luuksommers !! Thank you very much for reaching out!
Your bug report is very clear, I appreciate the detailed analysis. I'll see if I can replicate this behaviour and will come back to you when I have some results. That should be within a day or 2.

**Comment by luuksommers** [comment]
If you need more info to help the analysis, feel free to reach out, I'm
happy to help.

Op do 2 feb. 2023 19:08 schreef Dennis ***@***.***>:

**Comment by D-Inventor** [comment]
Hey @luuksommers I've attempted to replicate the behaviour you describe, based on your analysis. If I understand the pictures correctly, the memory increase is caused by the "continuation objects" created when awaiting the cached task.

So I debugged my application and fired 15000 requests to the same url with a redirect and compared the memory usage.
![screenshot of my memory analysis](https://user-images.githubusercontent.com/25585418/216540204-df5cf837-a9f3-4be7-b1ad-903ccd0cdfaf.png)

However, as you can see in my screenshot, the memory has barely increased by 10MB, which is hardly the 200MB that you're showing. And the graph shows that the memory pretty much stays around 500MB all the time.

Going into details, this seems to mostly point towards serilog:
![screenshot of memory increase](https://user-images.githubusercontent.com/25585418/216541218-dccf60db-fd02-429f-867b-1020e6004cfd.png)

So yeah, I'll be needing a little bit more information.
Mostly: Can you find out which URL this cache entry in your screenshot is of and can you find out what's on that url? Is it a redirect? Does the page not exist? Does the page **no longer** exist?

**Comment by D-Inventor** [comment]
I guess also anything potentially out of the ordinary, perhaps you've used a particular .NET Framework version? And how are you hosting your application?

**Comment by luuksommers** [comment]
We're running on targetFramework 4.7.2 on IIS 10. 
The url's are the javascript and css files from our application (static files) like '/assets/dist/layout.bundle.js?51e9fc3408c690a69e13'. This folder was not excluded, maybe that caused the issue. We've only excluded the media for now (`<add key="urlTracker:blockedUrlsList" value="/media" />`. There files do exists by the way. Each of these files has a ~200 mb / ~15000 entries in the cache. All other entries have only a couple of Kb's.

**Comment by D-Inventor** [comment]
Thanks for your response @luuksommers . I can see some memory increase when attempting to request static assets. However, any memory snapshots I make while debugging fail to yield the results that are in your picture.

If you have the chance, would you be able to drop the following code snippet into your project?

You might need a reference to the following NuGet packages if you don't have them already:
- Microsoft.Extensions.Caching.Abstractions 2.0.2
- Microsoft.Extensions.Caching.Memory 2.0.2

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Primitives;
using Umbraco.Core;
using Umbraco.Core.Composing;
using UrlTracker.Core.Caching;
using UrlTracker.Core.Configuration.Models;
using UrlTracker.Core.Configuration;
using UrlTracker.Core.Domain.Models;
using UrlTracker.Core.Intercepting.Models;

namespace UrlTracker.Resources.Website.CacheOverride
{
    [ComposeAfter(typeof(UrlTracker.Core.CoreComposer))]
    public class CacheOverrideComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.RegisterUnique<IInterceptCache, CacheOverrideInterceptCache>();
        }
    }

    public class CacheOverrideInterceptCache : IInterceptCache
    {
        private readonly IMemoryCache _cache;
        private CancellationTokenSource _clearTokenSource;
        private readonly object _lock = new object();
        private bool _disposedValue;

        public CacheOverrideInterceptCache(IConfiguration<UrlTrackerSettings> options)
        {
            _cache = new MemoryCache(Options.Create(new MemoryCacheOptions
            {
                SizeLimit = options.Value.MaxCachedIntercepts
            }));
            _clearTokenSource = new CancellationTokenSource();
        }

        public void Clear()
        {
            lock (_lock)
            {
                _clearTokenSource.Cancel();
                _clearTokenSource.Dispose();
                _clearTokenSource = new CancellationTokenSource();
            }
        }

        public Task<ICachableIntercept> GetOrCreateAsync(Url key, Func<Task<ICachableIntercept>> factory, MemoryCacheEntryOptions options = null)
        {
            return _cache.GetOrCreateAsync<ICachableIntercept>(key, entry =>
            {
                entry.SetOptions(options);
                entry.SetSize(entry.Size ?? 1);

                entry.AddExpirationToken(new CancellationChangeToken(_clearTokenSource.Token));

                return factory();
            });
        }

        #region IDisposable implementation
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposedValue)
            {
                if (disposing)
                {
                    _cache.Dispose();
                    _clearTokenSource.Dispose();
                }

                _disposedValue = true;
            }
        }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
        #endregion
    }
}
```

This overrides the cache with a different implementation that does not cache the tasks themselves, but just the results. This implementation however doesn't protect you from a so called 'cache stampede', which the original code is supposed to do.

I'd appreciate it if you could try this out and see if the memory issues persist or not.
If that fixes your issue, then at least there is a workaround.

If you find yourself willing to help me out with this issue, I'd like to invite you to fork or clone this repository and see if you can reproduce the behaviour that you experience. That would be incredibly helpful.

**Comment by D-Inventor** [comment]
Hi @luuksommers ! I haven't heard back from you in a while. Have you had a chance to try out the workaround?

**Comment by luuksommers** [comment]
Not yet, was very busy last week, so didn't have the time to implement it,
but I will try it and come back to you. I will be on holiday the next week
so give me a bit more time :-)

Op di 14 feb. 2023 09:08 schreef Dennis ***@***.***>:

**Comment by D-Inventor** [comment]
We're no longer going to improve the URL Tracker for Umbraco 8, except for security fixes, so I'm going to close this issue now as it specifically relates to Umbraco 8.

New updates are still being released for Umbraco 10 and 13
