### ISSUE TITLE
URL Tracker stop redirecting Invalid URLs to 404 page

### ISSUE THREAD

**Issue by CV-Dakshesh** [Infocaster/UrlTracker#125]
Hi

Using Umbraco 9.5 version with .net 6, When URL Tracker is enabled, it stops redirecting Invalid URLs to 404 custom page. though the URLs are not specifying in the URL Tracker list, It keeps on redirecting 404 requests to one specific application page. Which i think is invalid.

Though URL Tracker is enabled, It should redirect user to 404 page, If there is no matching page found in the application.

**Comment by D-Inventor** [comment]
Hi @Daxesh59 ! Thank you very much for reaching out. Are you able to reproduce this behaviour on a clean installation and could you provide some steps to reproduce this? That will help me to analyse the exact issue that you're experiencing

**Comment by D-Inventor** [comment]
@Daxesh59 I have identified the issue, this issue has been fixed in Umbraco 10. It is recommended to update to Umbraco 10 as Umbraco 9 is no longer supported.
