### ISSUE TITLE
js error on staging environment but not local

### ISSUE THREAD

**Issue by tom-activeis** [Infocaster/UrlTracker#128]
**Describe the bug**
_Using version: 10.2.1_
Works fine locally, when deploying to Azure App Service, angularjs error stops the dashboard from rendering 
Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.3/$controller/ctrlreg?p0=UrlTracker.OverviewController
    at umbraco-backoffice-js.js...
Hopefully it's something fairly trivial...

**To Reproduce**
1. Installed by using nuget package manager in Visual Studio, successfully includes <PackageReference Include="UrlTracker" Version="10.2.1" /> in the csproj file
2. Works fine locally :)
3. Deploy up to Azure App Service using build pipeline, no errors in nuget build, all 8 .dll files deployed as expected
4. On App Service hosted website gives js error described above and in screenshot

**Expected behavior**
Should work like on local server

**Screenshots**
![image](https://github.com/Infocaster/UrlTracker/assets/72741818/33371049-b216-448b-8577-daa39f333c4d)
![image](https://github.com/Infocaster/UrlTracker/assets/72741818/b78e23f2-d0d9-464b-a321-0b47266d3e9b)
![image](https://github.com/Infocaster/UrlTracker/assets/72741818/ddb6fa02-36f6-4b2f-b519-7d6d1728f75e)

**Desktop (please complete the following information):**
 - Browser : tried Chrome, Firefox, Edge... all same issue

**Additional context**
other packages UmbracoForms and Usync installed form nuget are working without errors

**Comment by D-Inventor** [comment]
Hi @tom-activeis ! Thanks a lot for reaching out! Most commonly, this error is caused by smidge, failing to bundle and minify a part of the static assets.

Have you had an older version of the URL Tracker installed before? Could you check out the App_Plugins folder and make sure that it does NOT have a folder called "UrlTracker" in there? Can you also verify that you have a folder in wwwroot/App_Plugins called "UrlTracker"?

**Comment by tom-activeis** [comment]
hi @D-Inventor ! many thanks for quick response, yes i did have a folder in wwwroot/App_Plugins called UrlTracker, 

no we didn't have an older version installed before
i went ahead and deleted it, and got the same issue ... restarted App Service, same issue ... am rerunning the build on our build pipeline to see if the build is including it, as it is not in our source/git repo ...

**Comment by tom-activeis** [comment]
UPDATE: got it working! many thanks for pointing us in the direction of smidge, we changed these settings https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/runtimeminificationsettings and it fixed itself
