### ISSUE TITLE
Does not work with Hebrew chars 

### ISSUE THREAD

**Issue by avialonn** [Infocaster/UrlTracker#142]
Hi all,
Redirect is not working for Hebrew. 
Working with latest version and Umbraco 10.x.
Any input will be appreciate.

aa

**Comment by D-Inventor** [comment]
Hi @avialonn , thank you for reaching out. Can you elaborate what you mean with "doesn't work"?

Before I can research your issue, I need the following information:
- exact version of umbraco that you use (not 10.x, but for example: 10.5.1)
- exact version of URL Tracker that you use (not latest, but for example: 10.3.0)
- summary of what happens
- what did you expect to happen
- steps to reproduce this on a clean Umbraco installation.

Once these are provided, I'll dive into it and see what I can do.

**Comment by D-Inventor** [comment]
Hi @avialonn , I haven't heard back from you in a while. Is this issue still relevant? If so, could you provide the information as per my previous comment?

**Comment by D-Inventor** [comment]
Closing this issue as stale. If this is still relevant, please reopen the issue with all provided information
