### ISSUE TITLE
HasDomainOnChildNodes doesn't work on Umbraco v11

### ISSUE THREAD

**Issue by HarrySpyrou** [Infocaster/UrlTracker#149]
**Describe the bug**
Umbraco 11.4.2 - Url Tracker: 11.0.1

I have the same bug on v11 as this one that I also reported:

[HasDomainOnChildNode does not work on multisite Umbraco v10](https://github.com/Infocaster/UrlTracker/issues/126)

Same exact issue seems to be chasing the plugin on 11 :D.

**Comment by D-Inventor** [comment]
Hi again! Thanks for letting me know! I think I simply forgot to merge my changes from the v10 fix into the v11 version. Version 11.1.0-beta.1 should release somewhere in the next hour if the build & release pipeline succeed. Could you check if that version works as expected? It should contain all fixes and changes that were made in v10.

**Comment by D-Inventor** [comment]
As it turns out, the release did in fact not succeed. I'll be back with another update when this is fixed

**Comment by D-Inventor** [comment]
Alright, now the release has succeeded, release [11.1.0-beta.1](https://www.nuget.org/packages/UrlTracker/11.1.0-beta0001) should have the fix included

**Comment by HarrySpyrou** [comment]
Yeah I just tested on Umbraco 11.4.2 and the beta seems to be working fine. I noticed on Nuget you have a 12 version, was wondering if you want to update that one too?

**Comment by D-Inventor** [comment]
Thanks for the test, I'll release a full version soon as well.

As for Umbraco 12, it should already have all the fixes. I had apparently already merged the fixes from v10 into v11, I had just forgotten to release a new v11 version. v12 was based on the v11 develop branch, and should therefore already be up-to-date.

**Comment by HarrySpyrou** [comment]
Awesome! Thanks a lot for the quick replies and fixes. Much appreciated. I can verify the beta you released works for me.

**Comment by D-Inventor** [comment]
Fix has been released in version 11.1.0
