### ISSUE TITLE
Validation Error, when Culture = "zh-Hant". Traditional Chinese

### ISSUE THREAD

**Issue by Artem-Savenkov** [Infocaster/UrlTracker#150]
_Using version: 10.2.1

1. create the redirect object with Culture property equal "zh-Hant".  "zh-Hant" is the ISO code for Traditional Chinese.
    var redirect = new Redirect 
    {
          Culture = "zh-Hant"
    } ;
2. try to Add this object to DB via that method 
    redirect = await _redirectService.AddAsync(redirect);
3. Get the Validation Exception:
    the field Culture must match the regular expression '^[a-z]{2}(?:-[A-Z]{2})?$'

**Expected behavior**
successfully added to DB the redirect object with Culture = "zh-Hant".

**Screenshots**
![image](https://github.com/Infocaster/UrlTracker/assets/43239136/fc1997ec-f9e4-47ae-ada8-0b0285b126f5)
![image](https://github.com/Infocaster/UrlTracker/assets/43239136/229adb49-a4ff-4b99-b8d6-43bfc0fd2aad)

**Comment by D-Inventor** [comment]
Hi @Artem-Savenkov thank you for reaching out! Your issue is very clear, I'll dive into it and come back to you when I have an update

**Comment by D-Inventor** [comment]
Hi @Artem-Savenkov We just released version 10.3.1-beta.1 with a fix for this issue. Are you interested to give it a try and see if that fixes the issue?

**Comment by Artem-Savenkov** [comment]
Hi Denis,
yes, this is the good news.
I will check this.

**Comment by Artem-Savenkov** [comment]
Hi @D-Inventor ,
I checked this flow.
it works great now.
Thanks ;)
