### ISSUE TITLE
Feature request: Redirects notifications 

### ISSUE THREAD

**Issue by aochmann** [Infocaster/UrlTracker#190]
Hi there! 👋🏻

I’m impressed with the package! I’d like to propose a feature: the ability to send custom Umbraco notifications when creating, updating, or deleting redirect. Currently, I’m integrating a redirect service for a headless project. With this feature, I could send webhooks containing paths to revalidate redirect details on both the frontend redirects definition and backend caches.

What are your thoughts on this?

Cheers,
Adrian

**Comment by D-Inventor** [comment]
Hi @aochmann ! I'm happy to hear that you're enjoying the URL Tracker 😊

I think notifications are a very logical addition to the URL Tracker. Extensibility has been a focus point of the plugin anyway, so it makes a lot of sense. I'm going to put this on the list, thank you for the suggestion!

If you need a quick workaround, I recommend making a decorator on the `IRedirectRepository`. From there, you can observe changes to all redirects, make your own notifications or build your logic directly. [Here is an example decorator that I built for caching](https://github.com/Infocaster/UrlTracker/blob/v13/develop/src/UrlTracker.Core.Caching.Memory/Database/DecoratorRedirectRepositoryCaching.cs).

Also, out of curiosity: which version of the URL Tracker do you use?

**Comment by D-Inventor** [comment]
Hi @aochmann ! In version _13.2.0-alpha0009_ of the URL Tracker, we've included an initial implementation for notifications while managing redirects. Check out an example in the source code here:
https://github.com/Infocaster/UrlTracker/blob/v13/feature/redesign/test/UrlTracker.Resources.Website/UrlTrackerNotifications/UrlTrackerNotificationHandler.cs

It would be awesome if you could give it a try and see if it works for you!

**Comment by D-Inventor** [comment]
Version 13.2.0 has been released, which includes this feature. I'm closing the issue now.
