### ISSUE TITLE
Import/export and download template not working

### ISSUE THREAD

**Issue by GajicAleksandar1** [Infocaster/UrlTracker#194]
Unable to use import/export
_Using version:13.2.0_ UrlTracker
_Using version:13.5.1_ Umbraco.Cms
When ever we try to use any of the functionality for import/export it downloads csv with the following content
`{"ExceptionMessage":"Value cannot be null. (Parameter 'element')","ExceptionType":null,"StackTrace":null}`

**To Reproduce**
1. Go to 'Url tracker back office page'
2. Click on 'Redirects.'
3. Click on 'Download a template.'
4. Notification appears: 'Template downloaded: Check your downloads to find the template'
5. File contains `{"ExceptionMessage":"Value cannot be null. (Parameter 'element')","ExceptionType":null,"StackTrace":null}`

**Expected behavior**
File to have correct content

**Additional context**
It works fine for manually adding redirects.

**Comment by D-Inventor** [comment]
Hi @GajicAleksandar1 !! Thank you for your report! We're gonna look into this and come back when we have an update!

**Comment by GajicAleksandar1** [comment]
Thanks @D-Inventor,
Update, I've debuged it a little bit, and found problem is when creating `CsvConfiguration`, `CurtuleInfo` is empty, but `CultureInfo.TextInfo.ListSeparator` has value `','`, but for some reason it throws this exception.

**Comment by GajicAleksandar1** [comment]
@D-Inventor we found the problem, after several hours of investigation. 
One of our projects were using `CsvHelper`, but version 33.0.1. Once we downgrade it to 30.0.1 it works fine.
