### ISSUE TITLE
Null UmbracoContext for static files

### ISSUE THREAD

**Issue by drpeck** [Infocaster/UrlTracker#41]
**Describe the bug**
_Using version: 9.0.0 with Umbraco 9.5.0_
When I setup a redirect for a static file (e.g. /BrochureRequest.html) that I wish to redirect to a piece of Umbraco content I get an error static.
```
NullReferenceException: Object reference not set to an instance of an object.
UrlTracker.Core.Abstractions.UmbracoContextReferenceAbstraction.GetResponseCode()
UrlTracker.Web.Processing.RedirectResponseInterceptHandler.ShouldIntercept()
UrlTracker.Web.Processing.RedirectResponseInterceptHandler.HandleAsync(RequestDelegate next, HttpContext context, ShallowRedirect intercept)
UrlTracker.Web.UrlTrackerMiddleware.DoInterceptAsync(HttpContext context, Url url)
UrlTracker.Web.UrlTrackerMiddleware.InvokeAsync(HttpContext context)
Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**To Reproduce**
1. Install Umbraco
2. Install UrlTracker
3. Have a static file (~/wwwroot/foo.html)
4. Visit the file in the browser (OK)
5. Setup a redirect in UrlTracker (e.g foo.html -> Content item) with a temporary redirect for debugging
6. Visit the file in the browser (OK: foo.html)
7. Delete the file
8. Visit the file in the browser (500: error stack as above)

**Expected behavior**
Ideally the request redirects, but if static files are not supported then a 404 would be expected not a 500

**Screenshots**
![image](https://user-images.githubusercontent.com/1196047/172368625-660b7e96-b521-4e21-a769-5be85e5560af.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Edge v102.0.1245.30 (Official build) (64-bit)

**Additional context**
I was playing around with trying to have static files served from a fallback location as I migrate a static HTML site to Umbraco, but this code should be fully removed and still getting the error.
```
/*
app.UseStaticFiles(new StaticFileOptions
            {
                // Look for static files in wwwroot and wwwrootFallback
                FileProvider = new CompositeFileProvider(
                    new PhysicalFileProvider(env.WebRootPath),
                    new PhysicalFileProvider(Path.Join(env.WebRootPath, "../wwwrootFallback")))
            });
*/
```

**Comment by D-Inventor** [comment]
Hi drpeck, thank you for reaching out!
I'll see if I can reproduce this error and then I'll get back to you!

**Comment by D-Inventor** [comment]
I'm having trouble reproducing this issue that you're describing. I've tried the steps in Umbraco 9.2 and in Umbraco 9.5.0, but in both cases, I get a 404 not found result, as it should. I see in your stacktrace that the issue must be on [this line in the code](https://github.com/Infocaster/UrlTracker/blob/v9/develop/src/UrlTracker.Core/Abstractions/UmbracoContextFactoryAbstraction.cs#L60). However, there should always be an umbraco context (It's the umbraco context **factory** after all), so I'm not sure how this issue might occur.

Are you doing anything specific in the startup that could explain the lack of umbraco context?

**Comment by D-Inventor** [comment]
> Ideally the request redirects, but if static files are not supported then a 404 would be expected

I agree, static files should be supported. The logic for redirecting static files is pretty much there, there's just that I don't know how to detect whether a url will create a 404 or not on static resources. I'm using the `UmbracoContext.PublishedRequest.ResponseStatusCode` for that and that seems to work fine on regular routes, but when I attempt to access a static file, the umbraco context returns null for the statuscode.
This could be submitted separately as a feature request, though I'd need some help to implement it.

**Comment by D-Inventor** [comment]
Upon further inspection, I think I've found the issue. Could you try out [version 9.0.1-beta0001](https://www.nuget.org/packages/UrlTracker/9.0.1-beta0001) for me and tell me if that fixes the exception?

I had apparently already fixed this issue on the develop branch, but hadn't released it yet.

**Comment by drpeck** [comment]
Kudos for the quick response. I'm not longer getting the 500 error, but instead get the 301/302 exactly as I would have anticipated. 👍
