### ISSUE TITLE
Not compatible with Umbraco Deploy (v9)

### ISSUE THREAD

**Issue by RIckvkersbergen** [Infocaster/UrlTracker#43]
**Describe the bug**
We are experiencing a version conflict. UrlTracker is not compatible with Umbraco Deploy 9.4. Because of this, we are not able to install the package. This is the error:

Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0 directly to project X to resolve this issue. 
X -> UrlTracker 9.0.0 -> UrlTracker.Core 9.0.0 -> Scrutor 4.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 6.0.0) 
 X -> Umbraco.Deploy.Cloud 9.4.0 -> Rebus.ServiceProvider 6.4.1 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0 && < 6.0.0).

Scrutor requires version 6 or higher while Rebus requires a version lower than 6. Is there a reason for this?

**Comment by D-Inventor** [comment]
Hi @RIckvkersbergen ! Thank you for reaching out.

There's no specific reason that we use this version of Scrutor other than keeping up-to-date with all the bug-fixes and improvements. I think it's definitely worth checking if a lower version supports Microsoft.Extensions.DependencyInjection.Abstractions 5.x. I've checked this for other packages, but I must've missed it for this one.

Could you check if the suggestion in the message that you get solves the issue? I think it's definitely something that I should look into, but if installing Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0 directly solves the issue for you, then I think that would be an acceptable workaround for now. Then I can include the downgrade of scrutor in the next big release. If it doesn't work, then perhaps I can include it in a minor release

**Comment by D-Inventor** [comment]
@RIckvkersbergen Can you please confirm if version [9.0.1-beta0002](https://www.nuget.org/packages/UrlTracker/9.0.1-beta0002) fixes your issue?

**Comment by D-Inventor** [comment]
I'm gonna close this issue and release 9.0.1 with the fix.

You can reopen the issue if it still doesn't work in the new version
