### ISSUE TITLE
Import failing on v10

### ISSUE THREAD

**Issue by Shadyn** [Infocaster/UrlTracker#67]
**Describe the bug**
_Using version: [e.g. 5.0.0-beta.4]_

**To Reproduce**
1. Export a .csv file from v10
2. Try to import a file that is formatted the same, or even the file itself
3. Error below is shown
4. An error occurred
Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader, CsvHelper.Configuration.CsvConfiguration)'.
Exception Details
System.MissingMethodException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader, CsvHelper.Configuration.CsvConfiguration)'. 

**Expected behavior**
A file formatted the same as an exported file from v10 should import

**Screenshots**
![image](https://user-images.githubusercontent.com/4174228/184211954-4bacc488-83ef-4a13-ac62-5940b9958c20.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 103.0.2
 - Version UrlTracker 10.0.2

**Comment by D-Inventor** [comment]
Hi @Shadyn Thank you very much for making the bug report!

It appears that your website has some trouble with CsvHelper. CsvHelper is a dependency of the URL Tracker. I've followed the steps that you've written down, but successfully imported the redirects from my .csv file.

I've found [this post on StackOverflow](https://stackoverflow.com/a/7578683/2853950) with several answers that are worth trying out. I think you might have an old version of the CsvHelper package on your server with a lower version. Could you check that you have at least version 28.0.1 of CsvHelper and try out the suggestions on that StackOverflow post?

If the post does not provide any answers, could you share with me which exact version of Umbraco you use and which packages you have installed besides the URL Tracker?

Looking forward to hear from you!
Dennis

**Comment by Shadyn** [comment]
Hi @D-Inventor,

I do have CSVHelper installed at the correct version according to nuget:

![image](https://user-images.githubusercontent.com/4174228/184223837-190e9b91-547c-445b-a4ab-914e1e4f1946.png)

I'll take a look on StackOverflow and see if I can find anything else.

**Comment by D-Inventor** [comment]
Hi @Shadyn It's been a week since your last update. Did you discover anything new? If not, can I still help you in some way?

**Comment by D-Inventor** [comment]
I'm closing this issue for now. If this issue is still relevant, feel free to reopen it with further analysis
