### ISSUE TITLE
Umbraco 10 : 405.0 - Method Not Allowed when trying to delete redirect.

### ISSUE THREAD

**Issue by Mustachio1** [Infocaster/UrlTracker#76]
Describe the bug
_Using version: 10.1.0

Have just installed version 10.1.0 to a website running Umbraco 10.2.0, and all seems to be working when it comes to adding and tracking redirects. But any time I try to click the bin icon to delete a redirect, or check them in the list and click the delete button, I can see an error in the web inspector - 405.0 - Method Not Allowed. The issue is that I can't delete the redirects I have created. Interestingly, I have no issue deleting the items from the Not Found screen.

To Reproduce

Install version 10.1.0 to an Umbraco site running Umbraco version 10.2.0. No configuration changes, just the defaults.

Screenshots

Error from web inspector
![image](https://user-images.githubusercontent.com/38067798/190388415-60d2ce81-e766-4254-b614-bc29bf028fe7.png)

**Comment by D-Inventor** [comment]
Hi @Mustachio1 ! Thank you very much for reaching out! Your issue is very clear. I'll see if I can reproduce this issue and then come back with the results. You should hear back from me either later today or tomorrow.

**Comment by Mustachio1** [comment]
@D-Inventor Thanks for getting back to me so quickly. Just as an experiment, I deployed the code to a staging environment (Azure web app), and the delete functionality works fine.

Potentially this is just some IIS setting related to HTTP verbage - I've had issues with DELETE verbs when developing APIs before.

Just wanted to give you a heads up in case you sink hours into investigating something that isn't an issue. I would say that I don't normally have to adjust any IIS settings related to WebDav or HTTP verbage with any other plugins or custom dashboard delete functionality, so maybe there's still something there to be looked into - I'm sure you'll know. 

Let me know what you think when you've had a chance to review. Cheers!

**Comment by Mustachio1** [comment]
One more thing, I realised after some reading online that I had a setting turned on on my laptop that I probably shouldn't have. 

Going to the "Turn windows features on or off" window, then:
Internet Information Services > 
World Wide Web Services > 
Common HTTP Features >

And making sure **WebDAV Publishing** is switched off. After doing this, everything is working as expected and deleting fine now.

So that resolved my issue and the plugin is working on my local dev environment and on the remote server. As I mentioned above, I'll leave it up to you to determine whether there is/isn't anything to be addressed, but I feel it was most likely just an issue with my IIS setup. 

Thanks again for your quick response, and sorry for any disruption.

**Comment by D-Inventor** [comment]
Thank you for your thorough analysis and good to see that you've managed to fix your issue. I did a quick check, just to be sure. All seems to work as it should, so I think your conclusions were correct. I'll close this issue as solved.
