### ISSUE TITLE
Culture property failing validation on submit

### ISSUE THREAD

**Issue by josey-baker** [Infocaster/UrlTracker#77]
**Describe the bug**
Using version: 5.2.0
I installed version 5.2.0 on Umbraco 8.13.0 using Nuget.
When I try and create a new redirect I receive the following error:
"Argument is invalid Parameter name: redirect"
Inner Exception:
System.ComponentModel.DataAnnotations.ValidationException: The field Culture must match the regular expression '^[a-z]{2}(?:-[A-Z]{2})?$'.

**To Reproduce**
1. Install version 5.2.0
2. Click on Create Redirect
3. Fill out the information and click Submit

**Expected behavior**
A redirect will be saved without error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.125

**Additional context**
I have cloned the repo and checked out the v8/main branch.  When I debug I see that the Culture property is set to "en-us".  If I comment out line 21 in Redirect.cs
//[RegularExpression(@"^[a-z]{2}(?:-[A-Z]{2})?$")]
the redirect gets saved without error and I see in the grid that the culture code is saved as en-us.  

Is there something with this version or a related library that is preventing this from validating?

![url error](https://user-images.githubusercontent.com/12897321/190485020-8492a5bb-ccfc-44a3-93da-bcfa8215ea31.JPG)
![url error 2](https://user-images.githubusercontent.com/12897321/190485040-572e9852-4eb6-4aee-81a5-160961bf8d73.JPG)

**Comment by D-Inventor** [comment]
Hi @josey-baker , thank you for reaching out! Your issue is very clear, I'll see if I can reproduce the issue and I'll get back to you with my results. That would be either later today or else tomorrow.

As for your question: The Umbraco content service and Umbraco context struggle to understand culture codes if they don't have the correct casing in several versions of Umbraco, so it's important to ensure that the culture value always has the correct casing, hence the validation rule. The fact that you receive this error indicates that the frontend generates bad culture codes and that's something that should be fixed.

**Comment by D-Inventor** [comment]
I have succesfully reproduced the issue. I'm going to work on a solution and create a prerelease when I have a fix.

**Comment by D-Inventor** [comment]
I just released version [5.2.1-beta.1](https://www.nuget.org/packages/UrlTracker/5.2.1-beta0001) with a fix. Do you have a chance to give it a try? I'd love to hear if this fixes the issue.

**Comment by josey-baker** [comment]
Your fix on [5.2.1-beta.1](https://www.nuget.org/packages/UrlTracker/5.2.1-beta0001) fixes the issue.  I included a new image which shows the culture as en-US.

![culture](https://user-images.githubusercontent.com/12897321/190669104-3a5099aa-29fe-4dd5-80b6-574ef1be2294.JPG)

**Comment by D-Inventor** [comment]
Thank you very much for confirming that the fix solves the issue! The fix is included in production [version 5.2.1](https://www.nuget.org/packages/UrlTracker/5.2.1) so I'll close the issue now.

Thank you for helping me make the URL Tracker even more awesome!
